=== andregclvs/DWeb2019/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project_record (info,workteam,abstract,deliverables,data) >

<!ELEMENT info (key_name,title,subtitle,begin_date,end_date,supervisor) >

<!ELEMENT key_name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ELEMENT workteam (elemento)+ >

<!ELEMENT elemento (nome,número_identificação,email,git_link) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT número_identificação (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT git_link (#PCDATA) >

<!ELEMENT abstract (parágrafo)* >
<!ELEMENT parágrafo (#PCDATA|link)* >
<!ELEMENT link (#PCDATA) >

<!ELEMENT deliverables (deliverable)* >
<!ELEMENT deliverable (#PCDATA) >

<!ELEMENT data (#PCDATA) >
        
<!ATTLIST supervisor url CDATA #REQUIRED >       
<!ATTLIST link url CDATA #REQUIRED >
<!ATTLIST deliverable url CDATA #REQUIRED >

=== andregclvs/DWeb2019/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "file:/C:/Users/andre/Desktop/DAW/aula1/PR.dtd">
<project_record>
    <info>
        <key_name>TP2</key_name>
        <title>XML, DTD e XPath</title>
        <subtitle>Projeto corresponde ao TPC da UC Desenvolvimento de Aplicações Web</subtitle>
        <begin_date>24/09/2019</begin_date>
        <end_date>01/10/2019</end_date>
        <supervisor url="mailto:jcr@di.uminho.pt">José Carlos Ramalho</supervisor>     
    </info>
    <workteam>
        <elemento>
            <nome>André da Silva Gonçalves</nome>
            <número_identificação>80368</número_identificação>
            <email>mailto:a80368@alunos.uminho.pt</email>
            <git_link>https://github.com/andregclvs</git_link>
        </elemento>
    </workteam>
    <abstract>
        <parágrafo>Resoluções propostas dos exercícios 6 e 7 da ficha 3 (<link url="http://www4.di.uminho.pt/~jcr/XML/CURSOS/PED2008/fichas/ficha3/index.html"></link>).</parágrafo>
        <parágrafo>Project Record para entrega dos trabalhos práticos.</parágrafo>
        <parágrafo>DTD do Project Record.</parágrafo>
    </abstract>
    <deliverables>
        <deliverable url="PR.dtd">DTD do Project Record (DTD)</deliverable>
        <deliverable url="ex6.txt">Solução exercício 6 da ficha 3 (TXT)</deliverable>
        <deliverable url="ex7.dtd">Solução exercício 7 da ficha 3 (DTD)</deliverable>
    </deliverables>
    <data>30-09-2019</data>
</project_record>
